[General]
network = MISTNetwork
sim-time-limit = 10s
record-eventlog = false

# record all scalars for comparative study
**.scalar-recording = true
**.vector-recording = false

# seed for reproducibility
seed-set = 0